// Finds which employers run a public job board on a crawlable job system, and writes a SQL seed for the `companies` table.
//   npx esbuild scripts/discover-boards.ts --bundle --platform=node --format=esm --outfile=.tmp/discover-boards.mjs
//   node .tmp/discover-boards.mjs "Canonical|GitLab|Grafana Labs|..." migrations/0004_seed_companies.sql
// Keep concurrency low: more than ~3 parallel requests made most fetches fail from the dev machine. Takes ~15 minutes for ~300 names.
import { writeFileSync } from "node:fs";
import { crawlBoard, inScope } from "../src/crawl";

const [namesArg, outPath] = process.argv.slice(2);
if (!namesArg || !outPath) {
  console.error('usage: node discover-boards.mjs "Name One|Name Two" out.sql');
  process.exit(1);
}

const names = [...new Set(namesArg.split("|").map((n) => n.trim()).filter(Boolean))];
// Path-based job systems only: subdomain-based ones (Breezy, Recruitee, Personio) stall on DNS for names that don't exist,
// and the pipeline discovers those from search results anyway.
const SYSTEMS = ["greenhouse", "lever", "ashby", "smartrecruiters", "workable"] as const;

const slugsFor = (name: string) => {
  const base = name.toLowerCase().replace(/[.'’]/g, "");
  return [...new Set([base.replace(/[^a-z0-9]+/g, ""), base.replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")])].filter((s) => s.length >= 3);
};

const jobs: (() => Promise<void>)[] = [];
const found = new Map<string, { ats: string; slug: string; total: number; italy: number; sponsor: number; africa: number; uk: number }>();
for (const name of names) {
  for (const slug of slugsFor(name)) {
    for (const ats of SYSTEMS) {
      jobs.push(async () => {
        const r = await crawlBoard({ ats, slug });
        if (r.status !== "ok" || r.jobs.length === 0) return;
        const italy = r.jobs.filter((j) => !inScope("italy-remote", j)).length;
        const sponsor = r.jobs.filter((j) => !inScope("sponsorship", j)).length;
        const africa = r.jobs.filter((j) => !inScope("africa-remote", j)).length;
        const uk = r.jobs.filter((j) => !inScope("uk-remote", j)).length;
        if (italy || sponsor || africa || uk) found.set(`${ats}:${slug}`, { ats, slug, total: r.jobs.length, italy, sponsor, africa, uk });
      });
    }
  }
}

console.log(`${names.length} names -> ${jobs.length} probes`);
await Promise.all(
  Array.from({ length: 3 }, async () => {
    while (jobs.length) await jobs.shift()!().catch(() => {});
  }),
);

const now = new Date().toISOString();
const rows = [...found.values()].sort((a, b) => b.italy - a.italy || b.total - a.total);
// africa_eligible/uk_eligible come straight from inScope() on the board's own listing — a deterministic location
// check, unlike `sponsors` (which needs sponsorship wording confirmed in a posting's actual text, so it's never
// guessed here and stays 0 until the pipeline confirms it live).
const sql = [
  "-- Seed for the company-board crawl (generated by scripts/discover-boards.ts). Boards that answered with at least one in-scope role.",
  ...rows.map(
    (r) =>
      `INSERT INTO companies (key, ats, slug, eu, first_seen, hits, sponsors, africa_eligible, uk_eligible) VALUES ('${r.ats}:${r.slug}', '${r.ats}', '${r.slug}', 0, '${now}', ${5 + Math.min(r.italy, 10)}, 0, ${r.africa > 0 ? 1 : 0}, ${r.uk > 0 ? 1 : 0}) ON CONFLICT(key) DO UPDATE SET hits = MAX(hits, excluded.hits), africa_eligible = MAX(africa_eligible, excluded.africa_eligible), uk_eligible = MAX(uk_eligible, excluded.uk_eligible);`,
  ),
];
writeFileSync(outPath, sql.join("\n") + "\n");
console.log(`wrote ${rows.length} boards to ${outPath}`);
