// One-time migration: existing postings from the Claude Artifact tracker's
// `db` collection, converted into seed.sql for the new D1-backed tracker.
// Run: node scripts/generate-seed.mjs > seed.sql

const postings = [
  {
    id: "anthropic-security-engineer-corporate-security", company: "Anthropic",
    title: "Security Engineer, Corporate Security", track: "sponsorship",
    location: "San Francisco, CA / Seattle, WA / New York, NY / Washington, DC (office-based/hybrid, not remote)",
    source_url: "https://job-boards.greenhouse.io/anthropic/jobs/5397319008",
    salary: "$320,000–$405,000 USD/year", score: 63, decision: "review", confidence: "medium",
    remote_eligibility: "n/a (sponsorship-relocation track) — sponsorship verified verbatim on Anthropic's own posting.",
    seniority_detected: "Senior, hands-on IC — candidate's 8+ years fits, no explicit years-minimum stated",
    matched_requirements: ["Identity and access management expertise", "Zero-trust access controls", "Python/scripting proficiency", "Threat modeling"],
    gaps: ["Core of role is endpoint security engineering (macOS/Windows/Linux/ChromeOS, MDM) — candidate's real experience is cloud security, not endpoint device management", "Office-based in one of 4 US cities, not remote", "Anthropic states it can't sponsor for every role/candidate even when it tries"],
    one_line_reason: "Verified sponsorship language directly from Anthropic's own posting and an exceptional salary, but the role's actual day-to-day (endpoint/MDM security) is a real mismatch with candidate's cloud/GRC background.",
    tailored_summary: "If pursuing, lead with IAM/zero-trust access control work from Vigilsec and Python scripting for security automation; be upfront that hands-on MDM/endpoint fleet management is not part of your background.",
    sponsorship_country: "USA", sponsorship_verified: 1,
    sponsorship_evidence: "We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa, and we retain an immigration lawyer to help with this. (quoted verbatim from Anthropic's own Greenhouse posting)",
    status: "Pending Review", status_changed_at: null, date_found: "2026-09-21T22:45:00Z",
  },
  {
    id: "anthropic-staff-security-engineer-risk-engineering", company: "Anthropic",
    title: "Staff+ Security Engineer, Risk Engineering", track: "sponsorship",
    location: "San Francisco, CA / New York, NY / Seattle, WA — hybrid, expect all staff in office ≥25% of the time",
    source_url: "https://job-boards.greenhouse.io/anthropic/jobs/5250052008",
    salary: "$320,000–$405,000 USD/year", score: 74, decision: "review", confidence: "medium",
    remote_eligibility: "n/a (sponsorship-relocation track) — sponsorship verified verbatim on Anthropic's own posting.",
    seniority_detected: "Staff+ IC, minimum 8 years security/software engineering required — a genuine stretch competitively",
    matched_requirements: ["Risk assessment and quantification — matches GRC/risk advisory background", "Infrastructure/cloud security — matches AWS Security Hub/GuardDuty/Config work at Vigilsec", "Identity/secrets management exposure", "Security automation"],
    gaps: ["Deep systems programming (Go/Rust/C/C++) requested alongside Python — candidate's automation work is Python/Bash", "Developer security / software supply-chain depth not strongly evidenced", "Staff+ level at a top AI lab is highly competitive — treat as a stretch application"],
    one_line_reason: "Strongest domain fit of the sponsorship-track candidates — GRC/risk/cloud-security overlap is real and sponsorship is verified verbatim — but Staff+ bar and systems-programming ask make it a genuine stretch.",
    tailored_summary: "Lead with risk assessment/quantification from GRC advisory work and cloud security automation at Vigilsec. Be upfront that Python/Bash is your automation depth, not Go/Rust/C/C++.",
    sponsorship_country: "USA", sponsorship_verified: 1,
    sponsorship_evidence: "We do sponsor visas! However, we aren't able to successfully sponsor visas for every role and every candidate. But if we make you an offer, we will make every reasonable effort to get you a visa. (quoted verbatim from Anthropic's own Greenhouse posting)",
    status: "Pending Review", status_changed_at: null, date_found: "2026-09-21T22:45:00Z",
  },
  {
    id: "checkmk-devsecops-cloud-security", company: "Checkmk (Checkmk GmbH)",
    title: "DevSecOps (m/f/d) Cloud Security", track: "italy-remote",
    location: "Remote / high flexibility with Munich, Germany office — team distributed across Germany, Italy, Austria, France, Spain, Poland, USA, Singapore, Malaysia",
    source_url: "https://checkmk-gmbh.jobs.personio.com/job/2526687",
    salary: "EUR 85,000-105,000/year", score: 85, decision: "apply", confidence: "medium",
    remote_eligibility: "likely eligible — Checkmk publicly states its team is distributed across Germany, Italy, Austria, France, Spain, Poland, USA, Singapore and Malaysia, explicitly including Italy. Could not load the live Personio posting directly this run to confirm the exact eligible-country list for this specific requisition.",
    seniority_detected: "Senior IC — candidate's 8+ years comfortably covers it",
    matched_requirements: ["AWS IAM boundaries, GuardDuty/Macie-style threat detection", "CI/CD security integration and shift-left automation", "Kubernetes/EKS security hardening", "Python/Bash scripting for security automation", "Business-fluent English required, German only 'a plus'"],
    gaps: ["AWS Organizations/Service Control Policies not directly evidenced", "Exact eligible-country list for this requisition not directly confirmed", "German listed as a plus, not required — not a hard-filter issue"],
    one_line_reason: "Best domain fit — DevSecOps/cloud security role heavy on AWS IAM, CI/CD security gates, and Kubernetes/EKS hardening, English-only language bar, real salary well above floor, Checkmk explicitly lists Italy among the countries its team works from.",
    tailored_summary: "Lead with EKS/Kubernetes security hardening and AWS Security Hub/GuardDuty/Config automation plus Terraform-based CI/CD policy gates. Confirm Italy is approved for this specific requisition before investing further time.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Pending Review", status_changed_at: null, date_found: "2026-09-21T10:15:00Z",
  },
  {
    id: "form3-senior-cloud-security-engineer-ai-resilience", company: "Form3",
    title: "Senior Cloud Security Engineer - AI Resilience & Security Enhancements (Contract)", track: "italy-remote",
    location: "100% Remote (Europe) — posting explicitly names Italy as one of the countries hired from",
    source_url: "https://boards-api.greenhouse.io/v1/boards/form3/jobs/8628358002",
    salary: "unclear — not stated (contract rate not listed)", score: 89, decision: "apply", confidence: "high",
    remote_eligibility: "eligible — posting states verbatim: \"Specifically hiring from: Austria, Bulgaria, Croatia, Cyprus, Estonia, Greece, Hungary, Italy, Latvia, Lithuania, Malta, Romania, Slovakia, and Slovenia.\" Italy named explicitly.",
    seniority_detected: "Senior level, hands-on IC — candidate's 8+ years fits well",
    matched_requirements: ["AWS platform security", "IAM, RBAC, least-privilege models", "CI/CD pipeline security", "Software supply chain security", "Kubernetes and Linux expertise", "Infrastructure as Code / policy-as-code"],
    gaps: ["This is a CONTRACT position, not permanent — confirm this fits before applying", "AI/ML platform security controls (desirable, not required) not evidenced", "Cryptographic key management depth not strongly evidenced", "No salary/day-rate stated"],
    one_line_reason: "Best-fitting posting found — Italy explicitly named as an eligible hire country, strong AWS/IAM/CI-CD/Kubernetes overlap, senior level matched. Only caveat is it's a contract, not permanent, role.",
    tailored_summary: "Lead with AWS Security Hub/GuardDuty/Config automation, Terraform-based CI/CD policy gates, and EKS/Kubernetes hardening. Confirm the contract term/day-rate meets expectations before applying.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Pending Review", status_changed_at: null, date_found: "2026-09-21T23:00:00Z",
  },
  {
    id: "jobandtalent-senior-application-security-engineer", company: "Job&Talent",
    title: "Senior Application Security Engineer", track: "italy-remote",
    location: "Remote, ±1hr CET flexibility (HQ Madrid)",
    source_url: "https://jobs.lever.co/jobandtalent/3b64145a-39a1-41c9-8b65-f8d5c9c1d5b6",
    salary: "unclear — not listed", score: 56, decision: "review", confidence: "low",
    remote_eligibility: "unclear — CET-timezone flexible (Italy fits timezone-wise) but eligible countries not explicitly stated",
    seniority_detected: "Senior, 3-4+ years required — candidate exceeds on paper",
    matched_requirements: ["general security engineering background", "CI/CD security automation exposure"],
    gaps: ["role is a dedicated Application Security specialization — not one of the candidate's core target families and not strongly evidenced", "no salary stated"],
    one_line_reason: "Seniority and general security background fit, but this is a deep AppSec specialization the candidate hasn't demonstrated — borderline.",
    tailored_summary: "If pursuing, lead with automated vulnerability scanning pipeline work at Soft Solutions S.R.L. and CI/CD policy gates at Vigilsec; honestly flag that dedicated SAST/threat-modeling/pen-testing depth is limited.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-21T00:00:00Z",
  },
  {
    id: "nebius-infrastructure-security-engineer", company: "Nebius",
    title: "Senior/Staff Infrastructure Security Engineer", track: "italy-remote",
    location: "Remote - Europe",
    source_url: "https://job-boards.greenhouse.io/embed/job_app?for=nebius&token=4537289101",
    salary: "unclear — not listed in posting", score: 78, decision: "apply", confidence: "medium",
    remote_eligibility: "likely eligible — posting is titled and scoped \"Remote - Europe\" with no country exclusions listed; exact Italy inclusion isn't spelled out verbatim.",
    seniority_detected: "Senior/Staff IC, 6+ years infrastructure/cloud/network security required — candidate's 8+ years clears this",
    matched_requirements: ["Cloud security architecture (containers, VMs, serverless, Kubernetes)", "IAM", "Security automation scripting (Python, Bash)", "Infrastructure-as-code security (Terraform)", "Kubernetes hardening"],
    gaps: ["Go scripting not evidenced", "Linux-level hardening (apparmor/seccomp) not directly evidenced", "Exact eligible-country list not spelled out — confirm Italy before investing significant application time", "No salary stated"],
    one_line_reason: "Verified live Greenhouse posting, English-only, Remote-Europe scope with strong IAM/Terraform/Kubernetes-hardening overlap and seniority well matched.",
    tailored_summary: "Lead with AWS Security Hub/GuardDuty/Config automation and Terraform-based CI/CD policy gates, plus EKS/Kubernetes hardening and Python/Bash security automation scripting.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Pending Review", status_changed_at: null, date_found: "2026-09-21T21:30:00Z",
  },
  {
    id: "prima-cyber-security-governance-specialist", company: "Prima",
    title: "Cyber Security Governance Specialist", track: "italy-remote",
    location: "Milan, Italy (remote flexible — Italy/Spain/UK)",
    source_url: "https://jobs.eu.lever.co/prima/47cfe444-120e-477f-b169-6dff57383874",
    salary: "€40,000–€50,000/year", score: 84, decision: "apply", confidence: "high",
    remote_eligibility: "eligible",
    seniority_detected: "Mid-level IC (2+ yrs min) — candidate exceeds the bar",
    matched_requirements: ["ISO 27001 gap assessments", "GDPR compliance work", "risk assessments & audits", "governance framework experience"],
    gaps: ["DORA specifics not confirmed", "no formal BCM/DR ownership", "AI-governance tooling unconfirmed", "CISSP/CISM/CRISC not held (nice-to-have only)"],
    one_line_reason: "Strong GRC/ISO27001/GDPR overlap, Italy-based remote role, salary within range — best match found this run.",
    tailored_summary: "Lead with ISO 27001 gap-assessment delivery via ciso.ikenga.ng and GDPR/audit-evidence work at Soft Solutions S.R.L.; acknowledge DORA and formal BCM as growth areas.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-20T00:00:00Z",
    tailored_cv_url: null, tailored_cv_filename: "Sebastine_Nnanemere_CV_Prima.pdf",
  },
  {
    id: "secfix-senior-information-security-specialist", company: "Secfix",
    title: "Senior Information Security Specialist", track: "italy-remote",
    location: "Remote, ±2 hours from Germany (GMT+1) time zone",
    source_url: "https://jobs.ashbyhq.com/secfix/7b5757b0-c685-4e74-969a-5dea888e13a0",
    salary: "unclear — not listed in available sources", score: 82, decision: "apply", confidence: "medium",
    remote_eligibility: "eligible — 100% remote, GMT+1 ±2hrs zone explicitly named, includes Italy",
    seniority_detected: "Senior IC, 5+ years GRC/InfoSec required — candidate exceeds at 8+ years",
    matched_requirements: ["ISO 27001 gap assessment / certification project experience", "SOC 2 compliance automation and audit evidence", "GDPR DPIAs and risk assessments", "Cloud posture across AWS/GCP/Azure", "C1/C2 English fluency required"],
    gaps: ["Posting wants 3+ full ISO 27001 certification projects led end-to-end — not confirmed at that count", "Hands-on experience with a commercial GRC platform not evidenced", "Salary not confirmed — verify meets floor before applying"],
    one_line_reason: "Only hard-filter-clean GRC/Cloud-Security posting this run with a genuine Italy-inclusive remote fit and English-only language requirement.",
    tailored_summary: "Lead with ISO 27001 gap-assessment delivery and SOC2/ISO27001 compliance automation at Vigilsec, plus GDPR DPIA work and multi-cloud posture experience.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-21T00:00:00Z",
  },
  {
    id: "td-synnex-cybersecurity-iam-zero-trust-architect", company: "TD SYNNEX",
    title: "Cybersecurity Architect – IAM, Zero Trust", track: "italy-remote",
    location: "Spain/Portugal/Italy — Remote",
    source_url: "https://synnex.wd5.myworkdayjobs.com/tdsynnexcareers/job/barcelona-spain/cybersecurity-iam---zero-trust-architect_r54386",
    salary: "unclear — not listed", score: 65, decision: "review", confidence: "low",
    remote_eligibility: "eligible (Italy named explicitly as a remote option)",
    seniority_detected: "unclear — requirements text didn't load (Workday SPA returned nothing to a plain fetch)",
    matched_requirements: ["IAM", "Zero Trust"],
    gaps: ["full requirements unknown — read the live posting before tailoring further"],
    one_line_reason: "Title and named remote-eligible countries (incl. Italy) are a strong IAM/Architect match, but requirements never loaded — score is provisional.",
    tailored_summary: "Requirements text didn't load (Workday SPA blocked the fetch) — read the live posting first. If it holds up, lead with Zero Trust architecture work.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-20T00:00:00Z",
    tailored_cv_filename: "Sebastine_Nnanemere_CV_TDSYNNEX.pdf",
  },
  {
    id: "transficc-security-compliance-specialist", company: "TransFICC",
    title: "Security Compliance Specialist", track: "italy-remote",
    location: "Remote First (office in London) — flexible remote working locations within UK/Europe",
    source_url: "https://jobs.ashbyhq.com/transficc/8a1232f8-e84b-4bdd-a861-73bb138078d9",
    salary: "up to £75,000 + shares + benefits", score: 82, decision: "apply", confidence: "medium",
    remote_eligibility: "eligible (broad UK/Europe remote, Italy not confirmed by name but not excluded)",
    seniority_detected: "4+ years required — candidate exceeds",
    matched_requirements: ["GRC/compliance experience", "ISO 27001 and SOC 2 process leadership", "security questionnaire response", "audit coordination"],
    gaps: ["DORA/NIS2 specifics not confirmed hands-on", "CISSP/CISM not held"],
    one_line_reason: "Strong GRC/ISO27001/SOC2 overlap, broad UK/Europe remote eligibility, real salary stated — second-best match in the tracker.",
    tailored_summary: "Lead with ISO 27001/SOC 2 process ownership and audit coordination; be upfront that DORA/NIS2 exposure is developing rather than deep.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-21T00:00:00Z",
  },
  {
    id: "usergems-senior-security-engineer", company: "UserGems",
    title: "Senior Security Engineer", track: "italy-remote",
    location: "Remote, Europe",
    source_url: "https://job-boards.greenhouse.io/usergems/jobs/6018876004",
    salary: "€80,000–€100,000/year", score: 74, decision: "review", confidence: "medium",
    remote_eligibility: "eligible (assumed — 'Remote Europe', Italy not explicitly excluded)",
    seniority_detected: "Senior, first dedicated security hire — matches",
    matched_requirements: ["SOC 2 / ISO 27001 familiarity", "AWS working knowledge", "vulnerability management", "incident response"],
    gaps: ["posting's 'critical requirement' is sole end-to-end ownership of a zero-exception SOC2/ISO audit — a real stretch", "secure code review / pen-testing depth unconfirmed"],
    one_line_reason: "Strong comp and scope, but the one 'critical' bar (sole zero-exception audit ownership) is a real stretch — worth a closer read.",
    tailored_summary: "Lead with SOC2/ISO27001 compliance automation and independent ISO27001 gap-assessment delivery; be honest that you've owned remediation/evidence rather than sole audit ownership.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-20T00:00:00Z",
    tailored_cv_filename: "Sebastine_Nnanemere_CV_UserGems.pdf",
  },
  {
    id: "ygo-cloud-security-engineer", company: "YGO",
    title: "Cloud Security Engineer", track: "italy-remote",
    location: "Remote, EU",
    source_url: "https://jobs.ashbyhq.com/ygo/e0b8615d-77e0-436d-86a1-99cdba9c8b53",
    salary: "unclear — not listed", score: 77, decision: "apply", confidence: "medium",
    remote_eligibility: "eligible (assumed — EU-wide remote, Italy not confirmed excluded)",
    seniority_detected: "5+ years required — candidate exceeds",
    matched_requirements: ["cloud security fundamentals", "IAM", "incident investigation", "5+ years hands-on security"],
    gaps: ["application security depth (SAST/DAST, secure code review) not strongly evidenced", "'engineering background essential' — candidate is automation/scripting-strong but not software-engineer by background", "no salary stated"],
    one_line_reason: "Good IAM/cloud/IR overlap and EU remote eligibility, but appsec depth and the engineering-background bar are open questions.",
    tailored_summary: "Lead with IAM governance, incident response, and EKS/cloud hardening; be upfront that appsec testing is a growth area.",
    sponsorship_country: null, sponsorship_verified: 0, sponsorship_evidence: null,
    status: "Applied", status_changed_at: "2026-09-21T00:00:00Z", date_found: "2026-09-20T00:00:00Z",
    tailored_cv_filename: "Sebastine_Nnanemere_CV_YGO.pdf",
  },
];

function esc(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return String(v);
  return "'" + String(v).replace(/'/g, "''") + "'";
}

const cols = [
  "id", "company", "title", "track", "location", "source_url", "salary", "score", "decision",
  "confidence", "remote_eligibility", "seniority_detected", "matched_requirements", "gaps",
  "one_line_reason", "tailored_summary", "sponsorship_country", "sponsorship_verified",
  "sponsorship_evidence", "status", "status_changed_at", "date_found",
  "tailored_cv_url", "tailored_cv_filename",
];

let out = "-- Migrated from the Claude Artifact tracker (claude.ai/artifact/RxsbsAxcDHnnT7zH4MZtna) on 2026-09-23.\n";
out += "DELETE FROM postings;\n\n";
for (const p of postings) {
  const row = cols.map((c) => {
    if (c === "matched_requirements" || c === "gaps") return esc(JSON.stringify(p[c] || []));
    if (c === "sponsorship_verified") return p[c] ? "1" : "0";
    return esc(p[c] ?? null);
  });
  out += `INSERT INTO postings (${cols.join(", ")}) VALUES (${row.join(", ")});\n`;
}

process.stdout.write(out);
