/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 4ec2e670b4e9d7dad08e29acac1784b9)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	ANTHROPIC_BASE_URL: string;
	ANTHROPIC_API_KEY: string;
	BRAVE_SEARCH_API_KEY: string;
	TRACKER_TOKEN: string;
	DEEPSEEK_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ANTHROPIC_BASE_URL" | "ANTHROPIC_API_KEY" | "BRAVE_SEARCH_API_KEY" | "TRACKER_TOKEN" | "DEEPSEEK_API_KEY">> {}
}
